import { Platform, StyleSheet } from 'react-native';

/** Premium dark visual language. Components consume only these semantic tokens. */
export const colors = {
  primary: '#D6B46A',
  primaryHover: '#E6C67E',
  primaryDark: '#B7924D',
  primaryDeep: '#F4E8C7',
  primaryLight: '#292417',
  primaryMid: '#51452B',
  primaryGlow: 'rgba(214, 180, 106, .18)',
  secondary: '#89A9A0',
  secondaryLight: '#1C2826',
  secondaryDark: '#B7D0C8',
  accent: '#D6B46A',
  accentLight: '#292417',
  accentDark: '#F4E8C7',
  background: '#101211',
  backgroundAlt: '#151817',
  backgroundDeep: '#0B0C0C',
  surface: '#1A1E1C',
  surfaceAlt: '#202522',
  surfaceMuted: '#272D29',
  surfaceGlass: 'rgba(26, 30, 28, .96)',
  text: '#F4F6F3',
  textSecondary: '#C7CECA',
  textTertiary: '#99A49E',
  textMuted: '#77837D',
  textOnPrimary: '#17140E',
  textOnDark: '#F4F6F3',
  border: '#303833',
  borderMid: '#424D46',
  borderStrong: '#68766D',
  borderFocus: '#D6B46A',
  success: '#75C99B',
  successLight: '#183427',
  warning: '#E4B468',
  warningLight: '#382B18',
  error: '#F08A81',
  errorLight: '#3A2020',
  info: '#85B9EA',
  infoLight: '#182B3F',
  overlay: 'rgba(0, 0, 0, .7)',
  overlayLight: 'rgba(16, 18, 17, .94)',
  tabBar: '#161A18',
} as const;

export const spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 48,
} as const;
export const radius = {
  xs: 6,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  pill: 999,
} as const;
export const typography = {
  display: {
    fontSize: 36,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -1,
    lineHeight: 43,
  },
  h1: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -0.5,
    lineHeight: 34,
  },
  h2: {
    fontSize: 22,
    fontWeight: '700' as const,
    color: colors.text,
    letterSpacing: -0.25,
    lineHeight: 28,
  },
  h3: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: colors.text,
    lineHeight: 24,
  },
  h4: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.text,
    lineHeight: 22,
  },
  body: {
    fontSize: 15,
    fontWeight: '400' as const,
    color: colors.text,
    lineHeight: 22,
  },
  bodyMedium: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.text,
    lineHeight: 22,
  },
  bodySmall: {
    fontSize: 13,
    fontWeight: '400' as const,
    color: colors.textSecondary,
    lineHeight: 19,
  },
  label: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  caption: {
    fontSize: 12,
    fontWeight: '400' as const,
    color: colors.textTertiary,
    lineHeight: 16,
  },
  mono: {
    fontSize: 13,
    fontWeight: '500' as const,
    fontFamily: Platform.select({
      ios: 'Menlo',
      android: 'monospace',
      default: 'monospace',
    }),
  },
  overline: {
    fontSize: 11,
    fontWeight: '700' as const,
    letterSpacing: 1,
    textTransform: 'uppercase' as const,
    color: colors.primary,
  },
} as const;
export const shadow = StyleSheet.create({
  none: {},
  xs: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.16,
    shadowRadius: 4,
    elevation: 1,
  },
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 3,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 20,
    elevation: 5,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 7,
  },
  brand: {
    shadowColor: '#D6B46A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
    elevation: 2,
  },
  inset: {},
});
export const layout = {
  screenPadding: spacing.xl,
  cardPadding: spacing.lg,
  sectionGap: spacing.xl,
  headerHeight: 64,
  tabBarHeight: Platform.OS === 'ios' ? 82 : 68,
  inputHeight: 52,
  buttonHeightLg: 52,
  buttonHeightMd: 44,
  buttonHeightSm: 36,
  minTouchTarget: 44,
} as const;
export const animation = { fast: 120, normal: 200, slow: 320 } as const;
